/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a09_JefeAreaContable;


import b_modelos.user;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author juan-jolo
 */
public class PanelAgregarRRHH extends javax.swing.JPanel {

    JPanel pn =null;
    /**
     * Creates new form PanelAgregarRRHH
     */
    public PanelAgregarRRHH() {
        initComponents();
        /*
        pn= new panelFormularioUsuario();
        pn.setSize(500, 500);
        pn.setLocation(0, 0);
        panelPrincipal.removeAll();
        panelPrincipal.add(pn,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        AgregarNuevoUsuario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        segundoN = new javax.swing.JTextField();
        tipocontrato = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aMaterno = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        areatrabajo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        primerN = new javax.swing.JTextField();
        aPaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sueldo = new javax.swing.JTextField();

        jLabel1.setText("Agregar RRHH");

        AgregarNuevoUsuario.setText("Aceptar");
        AgregarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNuevoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("ap.paterno");

        tipocontrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temporal 6 meses", "Temporal 12 meses", "Estable 5 años", "Estable 4 años", "Estable 3 años" }));

        jLabel9.setText("tipo de contrato");

        jLabel8.setText("sueldo");

        contraseña.setText("contraseña");

        areatrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            { "Jefe Produccion",
                "Atencion al Cliente",
                "Asistente Compras",
                "Proveedor",
                "Operario Almacen",
                "Jefe Compras",
                "Inspector Calidad",
                "Jefe Calidad",
                "Jefe Area Contable",
                "Operario Produccion"}
        ));
        areatrabajo.setSelectedIndex(0);

        jLabel2.setText("email");

        jLabel3.setText("segundos nombres");

        jLabel5.setText("ap.materno");

        jLabel7.setText("area de trabajo");

        jLabel11.setText("primer nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgregarNuevoUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(contraseña))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipocontrato, javax.swing.GroupLayout.Alignment.LEADING, 0, 156, Short.MAX_VALUE)
                            .addComponent(sueldo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areatrabajo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundoN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primerN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(primerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(segundoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(areatrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipocontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AgregarNuevoUsuario)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNuevoUsuarioActionPerformed
        /*
        JPanel pn = new JPanel();
        pn.setSize(PrincipalJefeContable.pn.getWidth(),PrincipalJefeContable.pn.getHeight());
        pn.setLocation(0, 0);
        pn.setBackground(Color.WHITE);
        */
        user u = new user ();
        u.setNombre1(primerN.getText());
        u.setNombre2(segundoN.getText());
        u.setAp_p(aPaterno.getText());
        u.setAp_m(aMaterno.getText());
        u.setPassword(pass.getText());
        if(sueldo.getText().equals("")){
            u.setSueldo(0);
        }else{
            u.setSueldo(Integer.parseInt(sueldo.getText()));
        }
        u.setTipo_contrato(String.valueOf(tipocontrato.getSelectedItem()));
        u.setEmail(email.getText());
        u.setTipo_usuario(String.valueOf(areatrabajo.getSelectedItem()));
        u.guardarBBDD();
        PanelGestionRRHH.panelPrincipal.removeAll();
        //PanelGestionRRHH.panelPrincipal.add(PrincipalJefeContable.pn,BorderLayout.CENTER);
        PanelGestionRRHH.panelPrincipal.revalidate();
        PanelGestionRRHH.panelPrincipal.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarNuevoUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNuevoUsuario;
    private javax.swing.JTextField aMaterno;
    private javax.swing.JTextField aPaterno;
    private javax.swing.JComboBox<String> areatrabajo;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField primerN;
    private javax.swing.JTextField segundoN;
    private javax.swing.JTextField sueldo;
    private javax.swing.JComboBox<String> tipocontrato;
    // End of variables declaration//GEN-END:variables
}
