/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a09_JefeAreaContable;

import b_modelos.user;

/**
 *
 * @author juan-jolo
 */
public class PanelModificarRRHH extends javax.swing.JPanel {
    
    private user UsuarioModificar;
    /**
     * Creates new form PanelModificarRRHH
     */
    public PanelModificarRRHH(user UsuarioModificar) {
        initComponents();
        this.UsuarioModificar = UsuarioModificar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        primerN = new javax.swing.JTextField();
        aPaterno = new javax.swing.JTextField();
        tipocontrato = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        aMaterno = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        areatrabajo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sueldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Modificar RRHH");

        jLabel3.setText("segundos nombres");

        primerN.setEditable(false);

        aPaterno.setEditable(false);

        tipocontrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temporal 6 meses", "Temporal 12 meses", "Estable 5 años", "Estable 4 años", "Estable 3 años" }));

        jLabel5.setText("ap.materno");

        jLabel9.setText("tipo de contrato");

        jLabel7.setText("area de trabajo");

        jLabel8.setText("sueldo");

        aMaterno.setEditable(false);

        contraseña.setText("contraseña");

        areatrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            { "Jefe Produccion",
                "Atencion al Cliente",
                "Asistente Compras",
                "Proveedor",
                "Operario Almacen",
                "Jefe Compras",
                "Inspector Calidad",
                "Jefe Calidad",
                "Jefe Area Contable",
                "Operario Produccion"}
        ));
        areatrabajo.setSelectedIndex(0);

        jLabel11.setText("primer nombre");

        jLabel2.setText("email");

        jLabel4.setText("ap.paterno");

        segundoN.setEditable(false);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("*En caso tenga un\nproblema con sus datos\npersonales, comunicarse\ncon el administrador de\nBase de Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(contraseña)
                            .addComponent(jLabel1))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipocontrato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sueldo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areatrabajo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aPaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(segundoN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primerN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(primerN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(segundoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(aMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(areatrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipocontrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        primerN.setText(UsuarioModificar.getNombre1());
        segundoN.setText(UsuarioModificar.getNombre2());
        aPaterno.setText(UsuarioModificar.getAp_p());
        aMaterno.setText(UsuarioModificar.getAp_m());
        areatrabajo.setSelectedItem(UsuarioModificar.getTipo_usuario());
        sueldo.setText(String.valueOf(UsuarioModificar.getSueldo()));
        tipocontrato.setSelectedItem(UsuarioModificar.getTipo_contrato());
        email.setText(UsuarioModificar.getEmail());
        pass.setText(UsuarioModificar.getPassword());
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user antes = UsuarioModificar;
        user despues = new user();
        despues.setSueldo(Float.parseFloat(sueldo.getText()));
        despues.setPassword(pass.getText());
        despues.setTipo_contrato(String.valueOf(tipocontrato.getSelectedItem()));
        despues.setEmail(email.getText());
        despues.setTipo_usuario(String.valueOf(areatrabajo.getSelectedItem()));
        Object [] atributos = {null,null,null,null,null};
        String [] valores = {null,null,null,null,null};
        if (!antes.getPassword().equals(despues.getPassword())){
            atributos[0]="Contraseña";
            valores[0]=despues.getPassword();
        }
        if (antes.getSueldo()!=despues.getSueldo()){
            atributos[1]="Sueldo";
            valores[1]=String.valueOf(despues.getSueldo());
        }
        if (!antes.getTipo_contrato().equals(despues.getTipo_contrato())){
            atributos[2]="TipoContrato";
            valores[2]=despues.getTipo_contrato();
        }
        if (!antes.getEmail().equals(despues.getEmail())){
            atributos[3]="Email";
            valores[3]=despues.getEmail();
        }
        if (!antes.getTipo_usuario().equals(despues.getTipo_usuario())){
            atributos[4]="tipoUsuario";
            valores[4]=despues.getTipo_usuario();
        }
        UsuarioModificar.modificarBBDD(atributos, valores);
        PanelGestionRRHH.panelPrincipal.removeAll();
        PanelGestionRRHH.panelPrincipal.revalidate();
        PanelGestionRRHH.panelPrincipal.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aMaterno;
    private javax.swing.JTextField aPaterno;
    private javax.swing.JComboBox<String> areatrabajo;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField primerN;
    private javax.swing.JTextField segundoN;
    private javax.swing.JTextField sueldo;
    private javax.swing.JComboBox<String> tipocontrato;
    // End of variables declaration//GEN-END:variables
}
