/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a01_Cliente;
import b_metodos_conexion.extraccion_tablas;
import java.awt.BorderLayout;
import static a01_Cliente.PrincipalCliente.panelPrincipal;
import b_modelos_para_tablas.ProduccionVSRequerimientos;
import java.util.ArrayList;

/**
 *
 * @author Argenis
 */
public class panelTablaPago extends javax.swing.JPanel {
    private ArrayList <ProduccionVSRequerimientos> pvsr = new ArrayList<ProduccionVSRequerimientos>();
    extraccion_tablas et = new extraccion_tablas();
    public static int id_resultante=0;
    /**
     * Creates new form panelTablaPago
     */
    public panelTablaPago() {
        initComponents();
        pvsr = et.lista_prod_vs_req();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID produccion ", "ID requerimiento", "Nombre Req", "Monto Req", "RUC empresa"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Seleccionar producto de la lista");

        jButton1.setText("Seleccionar Produccion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(324, 324, 324))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = jTable1.getSelectedRow();
        id_resultante=Integer.parseInt(et.FilaSeleccionadaID(n,
                "idProduccion ", " produccion"," requerimiento",
                "produccion.idrequerimiento=requerimiento.idrequerimiento "));
       panelPagarPedidoRealisado.textoIDProduccion=String.valueOf(id_resultante);
       PrincipalCliente.pn.setSize(500,500);
       PrincipalCliente.pn.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(PrincipalCliente.pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        int n= pvsr.size();
        String [][] arreglo = new String [n][5];
        for (int i = 0; i < n; i++) {
            arreglo[i][0]=String.valueOf(pvsr.get(i).getIdProduccion());
            arreglo[i][1]=String.valueOf(pvsr.get(i).getIdReq());
            arreglo[i][2]=pvsr.get(i).getNomReq();
            arreglo[i][3]=String.valueOf(pvsr.get(i).getMontoR());
            arreglo[i][4]=pvsr.get(i).getNomReq();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            arreglo,
            new String [] {
        "ID produccion ", "ID requerimiento", "Nombre Req", "Monto Req", "RUC empresa"
    }
        ));
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
