/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a01_Cliente;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import static a01_Cliente.PrincipalCliente.panelPrincipal;

/**
 *
 * @author Argenis
 */
public class panelManterPedido extends javax.swing.JPanel {

    /**
     * Creates new form panelManterPedido
     */
    public panelManterPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Buton_visualisar = new javax.swing.JButton();
        buton_modificar = new javax.swing.JButton();
        buton_eliminar = new javax.swing.JButton();

        jLabel1.setText("MANTENER PEDIDO ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Requerimiento", "Nombre", "Fecha de registro", "Fecha de entrega"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Buton_visualisar.setText("Visualizar");
        Buton_visualisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buton_visualisarActionPerformed(evt);
            }
        });

        buton_modificar.setText("Modificar");
        buton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_modificarActionPerformed(evt);
            }
        });

        buton_eliminar.setText("Eliminar");
        buton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(155, 155, 155))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Buton_visualisar)
                .addGap(28, 28, 28)
                .addComponent(buton_modificar)
                .addGap(32, 32, 32)
                .addComponent(buton_eliminar)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buton_visualisar)
                    .addComponent(buton_modificar)
                    .addComponent(buton_eliminar))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Buton_visualisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buton_visualisarActionPerformed
        // TODO add your handling code here:
        panelVisualisarPedido pn = new panelVisualisarPedido();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_Buton_visualisarActionPerformed

    private void buton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_modificarActionPerformed
        // TODO add your handling code here:
        
       panelManPed_ButModificar pn = new panelManPed_ButModificar();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_buton_modificarActionPerformed

    private void buton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_eliminarActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(this, "Se va a eliminar pedido");
        if (i==0){
           JOptionPane.showMessageDialog(this, "Se elimino ´pedido");
           panelManterPedido re = new panelManterPedido();
       re.setSize(500,500);
       re.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(re,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
       }else if(i==1){
           JOptionPane.showMessageDialog(this, "No se elimino ");
           panelBlanco re = new panelBlanco();
       re.setSize(500,500);
       re.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(re,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
       }
    }//GEN-LAST:event_buton_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buton_visualisar;
    private javax.swing.JButton buton_eliminar;
    private javax.swing.JButton buton_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
